spring:
  application:
    name: fx-transfer-lab
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  error:
    include-message: never
    include-stacktrace: never
